name: Update Dollar Price

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-price:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Fetch dollar price
      run: |
        # استفاده از API جایگزین که از خارج ایران قابل دسترسی است
        PRICE=$(curl -s "https://api.accessban.com/data/currency" | python -c "import json, sys; data=json.load(sys.stdin); print([x for x in data if x['code']=='USD'][0]['price'])")
        echo '{"price": '$PRICE', "last_updated": "'$(date +"%Y-%m-%d %H:%M:%S")'"}' > price.json
        
    - name: Commit and push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add price.json
        git commit -m "Update dollar price" || exit 0
        git push
